"""create interview session tables

Revision ID: 0455968cd08b
Revises: 64a761c98131
Create Date: 2026-09-29 20:57:09.268710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
# revision identifiers, used by Alembic.
revision: str = '0455968cd08b'
down_revision: Union[str, Sequence[str], None] = '64a761c98131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('parsed_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_gap_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('overall_match_score', sa.Float(), nullable=False),
    sa.Column('top_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_match_score BETWEEN 0.0 AND 1.0'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_gap_report_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('question_set', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_turn_number', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('created', 'in_progress', 'paused', 'completed', 'abandoned')"),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_gap_report_id'], ['skill_gap_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('readiness_level', sa.String(), nullable=True),
    sa.Column('dimension_averages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_progressions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('top_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('study_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_score BETWEEN 0.0 AND 10.0'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('question', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('answer_submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_turn_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_turn_id'], ['interview_turns.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_number')
    )
    op.create_table('answer_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('summary_feedback', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routing_hint', sa.String(), nullable=False),
    sa.Column('suggested_follow_up', sa.Text(), nullable=True),
    sa.Column('skill_level_inferred', sa.String(), nullable=True),
    sa.Column('evaluator_version', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_score BETWEEN 0.0 AND 10.0'),
    sa.CheckConstraint('weighted_score BETWEEN 0.0 AND 10.0'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['interview_turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_evaluations')
    op.drop_table('interview_turns')
    op.drop_table('final_reports')
    op.drop_table('interview_sessions')
    op.drop_table('skill_gap_reports')
    op.drop_table('jobs')
    op.drop_table('document_chunks')
    op.drop_table('candidates')
    # ### end Alembic commands ###
