"""Service layer for Interview Agent session management."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.models import (
    InterviewSession as InterviewSessionORM,
    InterviewTurn as InterviewTurnORM,
)
from app.core.schemas import (
    InterviewTurn,
    InterviewSession,
    QuestionSet,
    SessionStatus,
)


async def create_interview_session(
    db: AsyncSession,
    *,
    candidate_id: str,
    job_id: str,
    skill_gap_report_id: str,
    question_set: QuestionSet,
) -> InterviewSession:
    """
    Create and persist a new interview session.

    The QuestionSet is assumed to have already been generated by the
    Interview Agent's RAG question generator.
    """

    session_id = uuid.uuid4()
    started_at = datetime.now(timezone.utc)

    config = {
        "max_turns": 12,
        "allow_follow_ups": True,
    }

    session_orm = InterviewSessionORM(
        id=session_id,
        candidate_id=uuid.UUID(candidate_id),
        job_id=uuid.UUID(job_id),
        skill_gap_report_id=uuid.UUID(skill_gap_report_id),
        status=SessionStatus.CREATED.value,
        question_set=question_set.model_dump(mode="json"),
        current_turn_number=0,
        config=config,
        started_at=started_at,
    )

    db.add(session_orm)
    await db.commit()
    await db.refresh(session_orm)

    return _to_schema(session_orm)


async def get_interview_session(
    db: AsyncSession,
    *,
    session_id: str,
) -> InterviewSession | None:
    """Load an existing interview session by session ID."""

    session_uuid = uuid.UUID(session_id)

    result = await db.execute(
        select(InterviewSessionORM).where(
            InterviewSessionORM.id == session_uuid
        )
    )

    session_orm = result.scalar_one_or_none()

    if session_orm is None:
        return None

    return _to_schema(session_orm)


def _to_schema(session_orm: InterviewSessionORM) -> InterviewSession:
    """Convert the database session model into the API/session schema."""

    return InterviewSession(
        session_id=str(session_orm.id),
        candidate_id=str(session_orm.candidate_id),
        job_id=str(session_orm.job_id),
        skill_gap_report_id=(
            str(session_orm.skill_gap_report_id)
            if session_orm.skill_gap_report_id
            else None
        ),
        status=SessionStatus(session_orm.status),
        current_turn_number=session_orm.current_turn_number,
        turns=[],
        question_set=QuestionSet.model_validate(session_orm.question_set),
        session_started_at=session_orm.started_at,
        session_ended_at=session_orm.ended_at,
        config=session_orm.config,
    )
async def persist_interview_turn(
    db: AsyncSession,
    *,
    session: InterviewSession,
    turn: InterviewTurn,
) -> None:
    """Persist the current interview turn and its evaluation."""

    session_uuid = uuid.UUID(session.session_id)

    result = await db.execute(
        select(InterviewSessionORM).where(
            InterviewSessionORM.id == session_uuid
        )
    )
    session_orm = result.scalar_one_or_none()

    if session_orm is None:
        raise ValueError(
            f"Interview session {session.session_id} was not found."
        )

    # Update session state.
    session_orm.current_turn_number = session.current_turn_number
    session_orm.status = session.status.value
    session_orm.question_set = session.question_set.model_dump(mode="json")

    # Find the corresponding turn.
    turn_result = await db.execute(
        select(InterviewTurnORM).where(
            InterviewTurnORM.session_id == session_uuid,
            InterviewTurnORM.turn_number == turn.turn_number,
        )
    )
    turn_orm = turn_result.scalar_one_or_none()

    if turn_orm is None:
        turn_orm = InterviewTurnORM(
            id=uuid.uuid4(),
            session_id=session_uuid,
            turn_number=turn.turn_number,
            question=turn.question.model_dump(mode="json"),
            status=turn.status.value,
        )
        db.add(turn_orm)

    # Update answer information.
    turn_orm.question = turn.question.model_dump(mode="json")
    turn_orm.answer_text = turn.answer_text
    turn_orm.answer_started_at = turn.answer_started_at
    turn_orm.answer_submitted_at = turn.answer_submitted_at
    turn_orm.status = turn.status.value

    # Persist evaluation when available.
    if turn.evaluation is not None:
        turn_orm.evaluation = turn.evaluation.model_dump(mode="json")

    await db.commit()
    await db.refresh(turn_orm)

async def update_interview_session(
    db: AsyncSession,
    *,
    session: InterviewSession,
) -> None:
    """Persist the current interview session state."""

    session_uuid = uuid.UUID(session.session_id)

    result = await db.execute(
        select(InterviewSessionORM).where(
            InterviewSessionORM.id == session_uuid
        )
    )
    session_orm = result.scalar_one_or_none()

    if session_orm is None:
        raise ValueError(
            f"Interview session {session.session_id} was not found."
        )

    session_orm.status = session.status.value
    session_orm.current_turn_number = session.current_turn_number
    session_orm.question_set = session.question_set.model_dump(mode="json")

    await db.commit()
    await db.refresh(session_orm)